apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: ganache
  name: ganache
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ganache
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: ganache
    spec:
      containers:
      - image: schadokar/eth-ganache:1.0.0
        imagePullPolicy: ""
        name: ganache
        ports:
        - containerPort: 8545
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
