apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: ganache
  name: ganache
spec:
  ports:
  - name: "8545"
    port: 8545
    targetPort: 8545
  selector:
    io.kompose.service: ganache 
status:
  loadBalancer: {}
