apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: react
  name: react
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: react
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: react
    spec:
      containers:
      - image: schadokar/eth-react:1.0.0
        imagePullPolicy: ""
        name: react
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 100m
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
